using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace Problemy_Eulera
{
//Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:

//2^2=4, 2^3=8, 2^4=16, 2^5=32
//3^2=9, 3^3=27, 3^4=81, 3^5=243
//4^2=16, 4^3=64, 4^4=256, 4^5=1024
//5^2=25, 5^3=125, 5^4=625, 5^5=3125
//If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:

//4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125

//How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
    class Problem29 : IProblem
    {
        private const int start = 2;
        private const int stop = 100;

        public void PrintSolution()
        {
            Console.WriteLine($"Number of distinct terms: {Solution()}");
        }

        private int Solution()
        {
            List<BigInteger> numbers = new List<BigInteger>();

            for(int a = start; a <= stop; a++)
                for(int b = start; b <= stop; b++)
                {
                    BigInteger n = (BigInteger)Math.Pow(a, b);
                        numbers.Add(n);
                }

            numbers.Sort();

            for(int i = numbers.Count - 1; i > 0; i--)
            {
                if (numbers[i] == numbers[i - 1])
                    numbers.Remove(numbers[i]);
            }

            return numbers.Count;
        }

    }
}
